### PR TITLE
Update scraper

### PR DESCRIPTION
**Pull request by host505**
.ru uses cloudflare now, but .to not (yet).

Don't merge yet, I'd like to get some feedback, because I'm not sure that the .to mirror is globally accessed.
If it's heavily geoblocked, we'll have to utilize cfscrape on .ru instead.

### CODE REVIEW

**Comment by jewbmx** [comment]
No issues for me

**Comment by jewbmx** [comment]
Not sure if it matters but id remove the .com too while your at it. It directs to the .ru

**Comment by SerpentDrago** [comment]
Confirmed works fine (kodi 18 , latest released Redux + this scraper fix , Providers cleared)  Pulled up perfect good links!

**Comment by SerpentDrago** [comment]
is there no way to write a scraper so it can detect if there is cloudflare challenge then as needed use tools / modules available to get around it :?

**Comment by host505** [comment]
Yes, of course, many scrapers utilize cfscrape.py.
But I think scraping is gonna be slower, so as long as the non-cloudflared mirror works, it's the way to go imo.

**Comment by jewbmx** [comment]
Agreed. Im pretty sure cfscrape takes longer. I swap blocked domains out
for clean ones and save the blocked ones as a last resort. If ya think
about it the blocks are mainly used because of our kinda impact on their
domain so removing them from our scrapers is respectful. cfscrape isnt
really needed anyways because almost every website can replaced by another.

**Comment by jjgrech** [comment]
Changed .ru to .to and removed the .com base link. Pulling perfectly from here in S. Europe. I do expect that to change though, and since this is too good a debrid source to lose, perhaps cfscrape might be needed in the long run.

**Comment by jewbmx** [comment]
Yea I looked earlier for some more domains and thats the last for that one
lol so its gonna need to be fixed pretty soon with the cfscrape. Personally
I will probably just throw it in a folder because I dont use it anyways lol

**Comment by jewbmx** [comment]
Here ya go can someone test this for me lol
http://jewrepo.cf/JewRepo/4git/myrlsbb.py

**Comment by jjgrech** [comment]
LOL!!
It works mate. A lot.

RLSBB returned **24** 1080P links and **54** 720P links.

Yes. I call that a success ;)
Thank you sir!

**Comment by host505** [comment]
Yes, works.
But as I suspected I think it's slightly slower.
Results are exactly the same as .to.

**Comment by jjgrech** [comment]
I don't mind the extra 5 seconds ;) To be honest, didn't even notice it. But I can how they can build up if this happens to every source scraper.

Still manageable if kept for debrid sources I would contend.

**Comment by host505** [comment]
> I don't mind the extra 5 seconds

When you scrape 50+ sites, that time is very valuable.

**Comment by jewbmx** [comment]
Nice. If ya wanna learn to use cfscrape this is a good scraper for it. All i did was add the import at the top,

scraper = cfscrape.create_scraper()
Below sources = []

And change all
r = client.request(url)
To
r = scraper.get(url).content

**Comment by jewbmx** [comment]
No problem and thanks for the testing. Also thanks host505 for pointing out this scraper needed fixed lol i tested it the other day and put it in my works folder, would of been a month before i noticed lmao.

**Comment by JonnyGadd** [comment]
Thanks for this guys! Yes I believe another source that struggled to give results was 2DLL, usually every time it gives results, but this morning was struggling to get them

**Comment by jewbmx** [comment]
That should be 2ddl.ws and working proper.

**Comment by jewbmx** [comment]
Should.  Site wise i dont see any reasons for issues. App wise i dont use RD lol

**Comment by JonnyGadd** [comment]
It's not behaving like it usually would, struggling to get 2DLL sources currently, had to do 4 or 5 scrapes last night for them to eventually appear, cleared cache, providers etc maybe it's just a temporary thing and will sort itself out.

**Comment by jewbmx** [comment]
How many scrapers you got enabled? Might be a conflict with your pile

**Comment by JonnyGadd** [comment]
I have all debrid sources enabled, never had issues up til last night.

**Comment by jewbmx** [comment]
Its the scraper for some reason. Dont see any errors but its hella laggy

**Comment by jewbmx** [comment]
Someone could go step by step down the scraper doin a log scrape but i get
the feeling that its just the website. Might need to raise your timeout for
a day or two and see if that helps till its resolved.

**Comment by host505** [comment]
What does this conversation about another scraper has to do with this pr?
Your 'issue' (as you've been told so many times but refuse to accept) is that the site is slow lately. And sure Kodi add-ons scraping it doesn't help, so honestly if we wanted to help them we should kill off the scraper lol.
Please keep this on the issues section (although not an issue actually).

**Comment by JFG90** [comment]
Never said I wasn't accepting, Was answering someone else's questions, so I apologise, no need for the negativity towards me.

**Comment by host505** [comment]
The scraper name was not mentioned on pr header intentionally. They obviously don't like what we're doing, so didn't want to draw more attention. One can still see which scraper it's related to by just looking at the commit.
Anyway, they already opened 2 or 3 issues about their 'issue', no need to be mentioned all over the place.

**Comment by JFG90** [comment]
Like I've said I apologise didn't want anything to kick off, just want to get along with everyone here. I won't say no to more

**Comment by jewbmx** [comment]
If you read down the little chat this person said at the start a comment about the pr and then added the 2dll issue. Then ya got your random stoned comments by me while i try to take a look at the issue lol. I'll fix the newest issue tho by simply sticking to my own page and letting yall do your thing ;)

**Comment by host505** [comment]
I didn't say anything about you for trying to help, why are you making this such a big deal. I just mentioned the obvious that random prs are not places to talk about random issues, doesn't help anyone.
Besides as already mentioned he had already opened 2 or 3 issues about it.

**Comment by jewbmx** [comment]
Lol im just giving ya shit for being a meanie :) but also feel like any
chat option here is fair game for help since the idea of the github project
is to help people with scraper issues <3

**Comment by JFG90** [comment]
I understand that it's done now, did think being told that I refuse to accept it was uncalled for as I never stated that, maybe its the way it came across. Anyway it's done now so can we just drop it. Have a good evening both of you

**Comment by JFG90** [comment]
Jewbmx thanks for your looking into it for me earlier also. Very much appreciated

**Pull request merged**
