### PR TITLE
Added Lambda Icon

### PR DESCRIPTION
**Pull request by turtlestv**
Suggestion

### CODE REVIEW

**Comment by doko-desuka** [comment]
Ooh, from Half-Life!
I like it.

**Comment by SerpentDrago** [comment]
http://half-life.wikia.com/wiki/Lambda_logo 

yeh .. lol where do you think the name Lambda comes from ? haha

**Comment by doko-desuka** [comment]
From mathematics https://en.wikipedia.org/wiki/Lambda_calculus

**Comment by jewbmx** [comment]
I was thinking something like the gta5 LS icon lol

**Comment by jewbmx** [comment]
I like the half life idea too being a counter strike lover lmao

**Pull request merged**
