### PR TITLE
 sources_ lambdascrapers: replaced/added some scrapers by jewbmx

### PR DESCRIPTION
**Pull request by host505**
Settings & default.py adjusted accordingly.

### CODE REVIEW

**Comment by SerpentDrago** [comment]
Cartoonhd.py , https://cartoonhd.care/

I get a Error 502 Bad gateway on that site ?

**Comment by jewbmx** [comment]
Might be able to use cartoonhd.co

**Comment by SerpentDrago** [comment]
cartoonhd.co  loads for me , no idea if is compatible with the scraper .

**Comment by jewbmx** [comment]
Just took a quick glance at the .co website and the scraper. Looks like its a matchup but needs a few tweaks like the season episode codes with  /'s but needs to be  -'s. Also that .co site is the only one i can find lol they all went down or pushing a apk

**Comment by host505** [comment]
> Cartoonhd.py , https://cartoonhd.care/
I get a Error 502 Bad gateway on that site ?

Wow, they must just have changed it.
When I submitted the pr it was working for me.

**Comment by SerpentDrago** [comment]
Is it just me , or are you guys getting MASSIVE duplicates in the results . I'm talking absolutely 3/4 sometimes 5 , off almost every source  ?

**Comment by SerpentDrago** [comment]
Using host505 master of Lambdascrapers (that contains this pull request)   and fresh updated installs of every other module / addon related to exodus redux  in I-A-C's collection of repos . 
*All cache cleared / providers cleared .  Using LambdaScraper set , All providers enabled , All Debrid providers Enabled * 

Tested with the NEW Charmed , S01E02  (but it does this for any show i tried ) 
https://imgur.com/a/VdQOyHu

**Comment by host505** [comment]
All these sources on your pics  (darewatch, watchseries, xwatchseries etc) were there before my pr, I didn't put them in.
The ones I put (you can see from the commit which ones), I checked before if they already existed as sources.

**Comment by jewbmx** [comment]
I get lost in these pulls and whatnot at times but keep seeing my name pop up lol and wanted to point out that my name  is only in the scrapers i cleaned up to show info for last checked. If ya test one change my info out and add yours. It makes group projects a lil easier. Also watch what ya put in, some are just spare tires incase of a flat.

**Comment by host505** [comment]
I tested the scrapers I put in, they were all working at that time.
Not sure I understand your first part, you're suggesting we "mark" somehow the scrapers when we check them and are working?

**Comment by SerpentDrago** [comment]
jewbmx nice info ! 

Host505 , my bad !

**Pull request merged**
