### PR TITLE
 =Scraper Check 11-21-2018

### PR DESCRIPTION
**Pull request by jewbmx**
=Scraper Check 11-21-2018
forgot to keep track of my work like always so this ones gonna be different lol.
uploading all the working scrapers after im done since i cant tell where i been.
the trashbin of nojoys will be listed below and need removed to your nojoy fix folder.

_NoJoy
- Remove: mywatchseries.py (dupe of xwatchseries.py)
- Resolve error: freefmovies.py (finds but doesnt play.)
- Resolve error: freeputlockers.py (finds but doesnt play.)
- Dead Domain: iwatchflixxyz.py (no new domains found.)
- Dead Domain: plocker.py (havent looked for a new domain.)
- Broken: darewatch.py (needs cfscrape added still but got annoyed lol.)

### CODE REVIEW

**Comment by jewbmx** [comment]
Think i did that right lol. (First timer)

Only thing i did was fix normal scrapers and upload em to the folder, didnt do anything else.

**Comment by host505** [comment]
Nice!
Can you just delete mywatchseries? Just deleted in your fork and the change will append on this pr too.

**Comment by jewbmx** [comment]
So if i delete it now before the PR gets approved it will stay gone?

**Comment by jewbmx** [comment]
Did it anyways lol. Hoping this gets approved today so people can stop complaining about it and i also wanna remove the fork from my stuff lol

**Comment by host505** [comment]
Yeah you can do whatever changes you want on your forked repo until the pr gets merged and they will be included on this pr.

**Comment by jewbmx** [comment]
Nice. Im super git stupid lol but doesnt seem as confusing as it looks.

Someone will still need to remove the settings that might go with that scraper, i dont wanna touch anything besides actual scrapers :)

**Comment by host505** [comment]
Thought of that, but that scraper still exists in sources_incursion, so as long as we have that the setting should remain.

**Comment by bjgood** [comment]
jewbmx,
You should add putlockeronl in your pull request. It works fine if you add in a cfscrape fix.

**Comment by bjgood** [comment]
The quality of Fantastic Beasts is terrible. I know it's a cam but waiting for the sound quality to improve. Enjoy it if you can...;).

Later, dude. :).

**Comment by jewbmx** [comment]
Lol omg about 55mins in has a mic crackle that makes your groin ache.
Watched more the 10mins of it so I cant stop now lmao. Still better then
working on my addon

**Comment by doko-desuka** [comment]
> Fantastic Breasts movie

Who doesn't love some fantastic breasts?

> plocker.py

Wow, they usually redirect to the new domain, but no. This time they seem to be gone for good. I hope we weren't the cause of that.  
A pity, they were a good source. Few hosts but good ones, like MyCloud which I think was also owned by them.

Gotta look for fresh websites to make scrapers for. I tried to watch "The Incredibles 2" today and got only unplayable links.  
I can see the appeal of torrent / P2P.

**Comment by jewbmx** [comment]
As for your p2p torrent comment EEEEWWWWWWWWWWWWW *pukes on peepee*

But there is a few issues as of late that suck lol, theres a million addons being thrown up that all use the same scrapers or sites but barely anyone actually maintains their scrapers to keep up with the website changes. Pretty sure healthy scrapers do less harm then the outdated ones lol.

Then you got the people that just pile in everything they find without even reading the code, only opening the files to put their name in it. Be having 4 of the same broken scraper with just the name difference lmao. Them guys are a ghetto botnet/ddos.  I have actually looked into all the main named addons around and havent really seen any that do a nice job at maintaining their addon, last one i seen was placenta

**Comment by jewbmx** [comment]
Heads up to anyone that contributes to this project... imma do some non-en testing in the next day or so for my addon, and since the lack of em here is causein problems for people i am just gonna do a PR adding the files to the main folder set. Could also host em as a zip if someone wants to add em instead because i still wont be messing with the code outside a scraper.

**Comment by jewbmx** [comment]
> putlockeronl wheres this located @bjgood ? Im not seeing it lol

**Comment by bjgood** [comment]
Hi jewbmx,
It's in your script.module.Scrubs-2.3 zip file (I could have sworn it was here, too). I had been meaning to tell you about cfscrape being required for putlockeronl for a few days now but never got around to it. I hit your github everyday checking for any updates you may have posted. :).

BTW, plocker is working again...so I guess it being down was only temporary. 

Have a good one.

**Comment by doko-desuka** [comment]
@bjgood awesome.

**Comment by jewbmx** [comment]
I have all my scrapers updated on my phone but havent put a update up yet
because I got the menus messy right now from doing some changes and adding
tmdb. Also started adding some settings i like that are in ExoRedux but
havent finished em all the way or tested em all yet lol. Kinda started
doing too much at once. Doing the scraper work for here and the different
language ones is my breaktime from the stress of my addon lol

**Comment by jewbmx** [comment]
Dont know if i need to press another option to make this pr go thru but either way i am deleteing the fork from my repo this friday. I never got around to bjgoods request because im drowning myself over here lol but im sure someone else can. Im going to be focusing on my own stuff for a bit so i can get a big list of todos emptied.  Also hope this doesnt sound rude or nothing lol im just high.

**Comment by doko-desuka** [comment]
It's all good. You're supposed to just leave the PRs like that (as long as they're well written and can be merged without causing problems, hopefully) and the owners will get to them when they can.   
On occasion your PRs can get rejected or forgotten (it's happened to all of us), so it's best to submit them and move on, don't let it get personal.

**Comment by jewbmx** [comment]
Thanks doko just needed to hear that i can delete my fork folder lol, i dont mind when or if the pr gets approved as long as i dont undo the work by being OCD lmao.

On a side note i finally figured out that enable/disable rd option i was trying to get going lol. Made it into 2 menu items hidden unless nav.dev is enabled in my addon settings and added notifcations lol

**Comment by jewbmx** [comment]
I just put together a pairing tool for my exo fork if anyone wants to use it i uploaded it to my github page to share lol

https://github.com/jewbmx/ExoPairEm

**Comment by doko-desuka** [comment]
Cool stuff @jewbmx, I'm gonna take a look.

**Comment by jewbmx** [comment]
K imma start a issue in it for converstations about it and issues lol

**Comment by SerpentDrago** [comment]
@jewbmx is this updated enough to pull and merge to my fork ?

**Comment by jewbmx** [comment]
I uploaded to the wrong folder but o well lmao here ya go 

http://jewrepo.cf/JewRepo/4reddit/LS/

**Comment by jewbmx** [comment]
Notes are in the folder, ones that didnt work for me can be retested by others, did the check sorta quick lol

**Comment by SerpentDrago** [comment]
wow thats alot of changes and already fix's all mixed in , thanks for the work . 

theres no chance you can just make a PR ? is there ?  If not i'll try this week going though and making all your changes ! 


Thanks for you work

**Comment by jewbmx** [comment]
Lol np I keep proper support for my addon so its getting to be a quicker
process now.

As for the PR id rather not, im on a phone and it gets annoying lol.

Personally ive decided to quit helping other projects since noone seems to
stay as fluid as the sites

**Comment by SerpentDrago** [comment]
are all your fix's for the most part in your scrubsv2 addon ? if so i'll just grab from there :)

**Comment by jewbmx** [comment]
Yea i gotta stop playing with new scraper ideas and upload the latest
update tho lol. Been thinking about redoing most the scrapers for quality
info too

**Comment by jewbmx** [comment]
Wow 3 hours of messing around with invictus.ws and i finally realize that my damn RD is disabled in my settings lol hopefully all the files ive thrown away tonight didnt work

**Comment by jewbmx** [comment]
If anyone is interested in making new scrapers I have a big list of unused
sites I can share

**Comment by doko-desuka** [comment]
Sure, it's always good to know alternatives. It's a neverending uphill battle to have something that works.

I just think that with all the work involved, we should keep a private scraper list only for friends (like the MorpheusTV app owner did). If someone wants a pack with the updated scrapers, they'll need to come to Github and explicitly ask for it, as a way to demonstrate effort. Because going to Reddit to give it all away has a few problems...  
A) You just did a lot of work for free;  
B) You set yourself up for a copyright lawsuit from TV networks;  
C) You went on public and published yourself this work that can get you sued.  
So really, what's the point of doing all this?

@solarmoviez: some of these sites have difficult obfuscation mechanisms to avoid bots / scrapers leeching from them, so yeah. Another one I was looking into is ymovies.tv, it's also got some nice obfuscated javascript

PS: I hope @I-A-C is okay, they haven't posted at all on December.

**Comment by drchud** [comment]
> 
> 
> Sure, it's always good to know alternatives. It's a neverending uphill battle to have something that works.
> 
> I just think that with all the work involved, we should keep a private scraper list only for friends (like the MorpheusTV app owner did). If someone wants a pack with the updated scrapers, they'll need to come to Github and explicitly ask for it, as a way to demonstrate effort. Because going to Reddit to give it all away has a few problems...
> A) You just did a lot of work for free;
> B) You set yourself up for a copyright lawsuit from TV networks;
> C) You went on public and published yourself this work that can get you sued.
> So really, what's the point of doing all this?
> 
> @solarmoviez: some of these sites have difficult obfuscation mechanisms to avoid bots / scrapers leeching from them, so yeah. Another one I was looking into is ymovies.tv, it's also got some nice obfuscated javascript
> 
> PS: I hope @I-A-C is okay, they haven't posted at all on December.

@doko-desuka Sure one or two are good points, but of course there is going to be risk. Why is it you always want to get paid????
People in kodi world know the risk but enjoy THEIR HOBBY! Its not a career, job or a way to make money. Maybe you are not cut out for kodi, which is fine cause its not 4 everyone.

**Comment by doko-desuka** [comment]
@drchud it's not so much that it's free...
It's more like, we're setting ourselves up for some SERIOUS legal trouble, and for nothing in return.  
It's just not sustainable

**Comment by drchud** [comment]
@doko-desuka Well not fully true in my opinion. I understand times are different today than say 2 yrs ago. People get scared just cause another group or individual got a letter. And that usually happens cause...
A. They didn't take enough precautions to mask their identity. and slipped up.
B. Someone Ratted them out
C. They really didn't try to hide themselves in the first place. Basically they didn't give a shit.

I believe there was an individual they said he got a letter sometime in the middle of this year. So he stopped developing. Guess what, he was both an A and C for sure. Sad really cause he was good. I was even able to find a boatload of info on him.

On the flip side you have others that have been in kodi 3rd party dev. for a long time now. And they are fine. Usually quiet and keep to themselves.

If its not about money, or getting paid then why do you keep bringing that up? So are you too good to take a couple hrs if that to write a scraper for an addon? Not worth your time or what? 

Here is another example of a post from a4k that you wrote:

> Maybe.
> To be honest I think there's a need for an Exodus fork written from scratch, focused on being lightweight  performant.
> 
> You have Gaia as the high-end ultra-featured swiss army knife.
> There should be a low-end addon for people that don't care about lots of features and just want a basic set: support for debrid and free hosters, trakt integration and maybe that's it.
> 
> But that would be a sizeable task, and for zero compensation (unpaid) :(


Now again you are basically saying, since im not getting paid.....its not worth developing right?
Right or am i wrong?

**Comment by SerpentDrago** [comment]
I think all @doko-desuka is saying is , because of all the take down bots / sites going offline seemingly every other day .  Its becoming LIKE   a full time job . and as this job is unpaid . its just not worth it anymore . I can def understand that . 

Its not that he expects compensation . its just such a headache and no longer fun with all the legal shit to worry about ontop of constant maintance

**Comment by doko-desuka** [comment]
@drchud if I'm this way, imagine how the people working on TV and movies must feel towards pirates lol.

**Comment by rrosajp** [comment]
@doko-desuka @SerpentDrago @drchud @jewbmx @host505 
long time user start learning to code scraper 
this one is good tutorial 
(https://www.youtube.com/watch?v=aoztiHVZzng )
but its basic we need more specific to the issue  they create on web page  
 so more people involve eventually and that will have hard to go after all !
decentralize knowledge will be the future . instead of one or 2 guys work on one project.
it's just my two cents .
thaks u all for doing what u can.

**Comment by drchud** [comment]
@SerpentDrago Man its not that hard, you're exaggerating. Trust me i know. So once in a while a site closes down, no big deal you find more. Maybe a couple scrapers need a major fix every couple weeks, no big deal. 

I have a full time job, a life and still find time to run and fix my addon. And lots of people were doing it before me. So please don't give me that crap. If you cant see my point, you're hopeless too. Even though this project is dead and has been, Doko's attitude is toxic for the kodi scene.

**Comment by drchud** [comment]
@doko-desuka Im sure you know how they feel, cause you're acting like them. Are you a snitch? I do find it strange that you made a couple scrapers and you have this type of attitude.

**Comment by jewbmx** [comment]
Rosa there is about 3 more decent videos you can watch to learn some more, Maud has 1 or 2 more that i learned from. As for actual files you can get about 2 or 3 templates as well but none of them will help much. Open a few scrapers and their websites source code to learn how the scrapers do their thing and you will start to see what needs changed for scrapers to work, hard part is learning the modules lol. Every scraper is a template in the long run because a few light changes can make a whole new scraper for ya if you match the site to the right one thats already made

**Comment by jewbmx** [comment]
Seems like this projects dead so someone might wanna pick up the torch atleast for a bit lol.

If anyone needs me you can hit me up on my repo issues. Gonna have a scraper chat going anyways for some of the stumped moments like today

**Comment by 13Clowns** [comment]
@jewbmx was thinking the same. I'm more then happy to fork it and update PR's as they come in. If and when IAC comes back it all theirs.

**Comment by 13Clowns** [comment]
Forked and repo setup. send PR's and I'l update. 

https://github.com/13Clowns/_scrapers

**Comment by 13Clowns** [comment]
@jewbmx thanks didn't it was being updated there. Appreciate the direction.

**Comment by jewbmx** [comment]
Np, dont know if Serpent plans to update the version so you can probably fork that one and clean it up to be the new update.

I still dont use this but feel bad for the end users that do lol

**Comment by jewbmx** [comment]
Head up, if you use the gowatch hd scraper you should disable it for a day or so, both io and co are getting slammed and seem to be havin issues with their traffic

**Comment by jewbmx** [comment]
Honestly shouldnt need that. If LS is updated then everything should be
fine. Also no one knows if iac if even done lol the person could just be on
holiday.

**Comment by JFG90** [comment]
Good point this is very true, it's only been a couple of weeks or so since we last had an update? Everyone is entitled to a break 😂

**Comment by doko-desuka** [comment]
Heads up gowatchseries changed address, if you go to it it redirects to the new one.

**Comment by SerpentDrago** [comment]
anyone is welcome to fork. just keep the neutrality.   I've tried doing most pr's i came across blindly. no guarantees it's stable.

**Pull request closed without merging**
